fr = open('rosalind_ini2.txt', "r")
fw = open('rosalind_ini2.res.txt', "w")
line = fr.read()
values = line.split()
a = int(values[0])
b = int(values[1])
fw.write(str(a**2 + b**2))
fr.close()
fw.close()